[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Rob Day <rkd@rkd.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
libc = "0.2"
x11 = "2"
