[package]
name = "hash_speed_demo"
version = "0.1.0"
authors = ["Rob Day <rkd@rkd.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1"

[[bench]]
name = "hashing"
harness = false
